<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Build.Framework" HintPath="$(MSBuildToolsPath)\Microsoft.Build.Framework.dll" Private="false" />
    <Reference Include="Microsoft.Build.Utilities.Core" HintPath="$(MSBuildToolsPath)\Microsoft.Build.Utilities.Core.dll" Private="false" />
  </ItemGroup>
</Project>
