using System.Text;
using Maliev.ShadcnBlazor.Theming;
using Maliev.ShadcnBlazor.Components.Styling;

namespace Maliev.ShadcnBlazor.Showcase.Export;

public static class ThemeStudioCodeGenerator
{
    public static string WriteJson(ShadcnThemeDocument document) =>
        ShadcnThemeDocumentSerializer.Serialize(document);

    public static string WriteVisualStyleSnippet(
        ShadcnVisualStyle visualStyle,
        ShadcnColorTreatment colorTreatment,
        ShadcnDepthTreatment depth,
        ShadcnMotionTreatment motion,
        ShadcnStyleIntensity intensity)
    {
        ValidateEnum(visualStyle, nameof(visualStyle));
        ValidateEnum(colorTreatment, nameof(colorTreatment));
        ValidateEnum(depth, nameof(depth));
        ValidateEnum(motion, nameof(motion));
        ValidateEnum(intensity, nameof(intensity));

        return $"""
            @using Maliev.ShadcnBlazor.Components.Styling

            <ShadcnVisualStyleScope VisualStyle="ShadcnVisualStyle.{visualStyle}"
                                    ColorTreatment="ShadcnColorTreatment.{colorTreatment}"
                                    Depth="ShadcnDepthTreatment.{depth}"
                                    Motion="ShadcnMotionTreatment.{motion}"
                                    Intensity="ShadcnStyleIntensity.{intensity}">
                @* Place any Maliev.ShadcnBlazor components here. *@
            </ShadcnVisualStyleScope>
            """;
    }

    public static string WriteCSharp(ShadcnThemeDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);
        var validation = ShadcnThemeDocumentValidator.Validate(document);
        if (!validation.IsValid)
            throw new ArgumentException("A valid theme document is required.", nameof(document));

        var themeExpression = ShadcnThemeCSharpWriter.Write(document.Theme).TrimEnd();
        if (themeExpression.EndsWith(';'))
            themeExpression = themeExpression[..^1];

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by Maliev.ShadcnBlazor Theme Studio.");
        builder.AppendLine("// The JSON export is the portable source of truth for this configuration.");
        builder.AppendLine("// Program.cs: builder.Services.AddMalievShadcn(MalievShadcnTheme.Configure);");
        builder.AppendLine("using System;");
        builder.AppendLine("using Maliev.ShadcnBlazor;");
        builder.AppendLine("using Maliev.ShadcnBlazor.Theming;");
        builder.AppendLine();
        builder.AppendLine("namespace YourApp.Theming;");
        builder.AppendLine();
        builder.AppendLine("public static class MalievShadcnTheme");
        builder.AppendLine("{");
        builder.Append("    public const string Preset = ").Append(ToLiteral(document.Application.Preset)).AppendLine(";");
        builder.Append("    public const string Style = ").Append(ToLiteral(document.Application.Style)).AppendLine(";");
        builder.Append("    public const string BaseColor = ").Append(ToLiteral(document.Application.BaseColor)).AppendLine(";");
        builder.Append("    public const string IconLibrary = ").Append(ToLiteral(document.Application.IconLibrary)).AppendLine(";");
        builder.Append("    public const string MenuAccent = ").Append(ToLiteral(document.Application.MenuAccent)).AppendLine(";");
        builder.Append("    public const string MenuColor = ").Append(ToLiteral(document.Application.MenuColor)).AppendLine(";");
        builder.Append("    public const string MonospaceFontFamily = ").Append(ToLiteral(document.Theme.Metrics.MonospaceFontFamily)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    public static ShadcnTheme Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return " + Indent(themeExpression, 8) + ";");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static void Configure(ShadcnOptions options)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(options);");
        builder.Append("        options.FontFamily = ").Append(ToLiteral(document.Theme.Metrics.FontFamily)).AppendLine(";");
        builder.Append("        options.DefaultDarkMode = ").Append(document.Application.DefaultDarkMode ? "true" : "false").AppendLine(";");
        builder.Append("        options.DefaultDirection = ShadcnDirection.").Append(document.Application.DefaultDirection).AppendLine(";");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToLiteral(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static string Indent(string value, int spaces) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n')
            .Select(line => new string(' ', spaces) + line)
            .Aggregate(new StringBuilder(), (builder, line) => builder.AppendLine(line))
            .ToString()
            .TrimEnd();

    private static void ValidateEnum<T>(T value, string parameterName) where T : struct, Enum
    {
        if (!Enum.IsDefined(value))
            throw new ArgumentOutOfRangeException(parameterName, value, "Unsupported visual style option.");
    }

}
