using System.Text;
using Maliev.ShadcnBlazor.Showcase.Theming;
using Maliev.ShadcnBlazor.Theming;

namespace Maliev.ShadcnBlazor.Showcase.Export;

public static class ThemeStudioCodeGenerator
{
    public static string WriteJson(ThemeStudioGeneratorConfig config) =>
        ThemeStudioGeneratorConfigSerializer.Serialize(config);

    public static string WriteCSharp(ThemeStudioGeneratorConfig config)
    {
        ArgumentNullException.ThrowIfNull(config);
        ThemeStudioGeneratorConfigSerializer.Validate(config);

        var themeExpression = ShadcnThemeCSharpWriter.Write(config.Theme).TrimEnd();
        if (themeExpression.EndsWith(';'))
            themeExpression = themeExpression[..^1];

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by Maliev.ShadcnBlazor Theme Studio.");
        builder.AppendLine("// The JSON export is the portable source of truth for this configuration.");
        builder.AppendLine("// Program.cs: builder.Services.AddMalievShadcn(MalievShadcnTheme.Configure);");
        builder.AppendLine("using System;");
        builder.AppendLine("using Maliev.ShadcnBlazor;");
        builder.AppendLine("using Maliev.ShadcnBlazor.Theming;");
        builder.AppendLine();
        builder.AppendLine("namespace YourApp.Theming;");
        builder.AppendLine();
        builder.AppendLine("public static class MalievShadcnTheme");
        builder.AppendLine("{");
        builder.Append("    public const string Preset = ").Append(ToLiteral(config.Preset)).AppendLine(";");
        builder.Append("    public const string Style = ").Append(ToLiteral(config.Style)).AppendLine(";");
        builder.Append("    public const string BaseColor = ").Append(ToLiteral(config.BaseColor)).AppendLine(";");
        builder.Append("    public const string IconLibrary = ").Append(ToLiteral(ToKebabCase(config.IconLibrary))).AppendLine(";");
        builder.Append("    public const string MenuAccent = ").Append(ToLiteral(ToKebabCase(config.MenuAccent))).AppendLine(";");
        builder.Append("    public const string MenuColor = ").Append(ToLiteral(ToKebabCase(config.MenuColor))).AppendLine(";");
        builder.Append("    public const string MonospaceFontFamily = ").Append(ToLiteral(config.MonospaceFontFamily)).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    public static ShadcnTheme Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return " + Indent(themeExpression, 8) + ";");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static void Configure(ShadcnOptions options)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(options);");
        builder.Append("        options.FontFamily = ").Append(ToLiteral(config.FontFamily)).AppendLine(";");
        builder.AppendLine("        options.DefaultDarkMode = false;");
        builder.AppendLine("        options.DefaultDirection = ShadcnDirection.LeftToRight;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToLiteral(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static string Indent(string value, int spaces) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n')
            .Select(line => new string(' ', spaces) + line)
            .Aggregate(new StringBuilder(), (builder, line) => builder.AppendLine(line))
            .ToString()
            .TrimEnd();

    private static string ToKebabCase<T>(T value) where T : struct, Enum =>
        value.ToString().ToLowerInvariant();
}
